version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mindbridge-postgres
    environment:
      POSTGRES_USER: mindbridge
      POSTGRES_PASSWORD: mindbridge_secure_password
      POSTGRES_DB: mindbridge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mindbridge"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mindbridge-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mindbridge-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mindbridge-network

  # MindBridge API
  api:
    build: .
    container_name: mindbridge-api
    ports:
      - "8000:8000"
    environment:
      # Database
      DATABASE_URL: postgresql+asyncpg://mindbridge:mindbridge_secure_password@postgres:5432/mindbridge
      
      # Redis
      REDIS_URL: redis://redis:6379
      
      # Security
      SECRET_KEY: your-super-secret-key-change-in-production-please
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      
      # Environment
      ENVIRONMENT: development
      
      # CORS
      ALLOWED_HOSTS: localhost,127.0.0.1
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mindbridge-network

  # pgAdmin (Optional - für Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mindbridge-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mindbridge.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mindbridge-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  mindbridge-network:
    driver: bridge
