apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mentalhealth
  labels:
    app: grafana
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: false
      jsonData:
        timeInterval: "5s"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: mentalhealth
  labels:
    app: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards

  kubernetes-cluster.json: |
    {
      "dashboard": {
        "title": "Kubernetes Cluster Overview",
        "tags": ["kubernetes"],
        "timezone": "browser",
        "panels": [
          {
            "title": "Cluster CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(container_cpu_usage_seconds_total[5m]))"
              }
            ]
          },
          {
            "title": "Cluster Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(container_memory_usage_bytes)"
              }
            ]
          }
        ]
      }
    }

  postgresql-dashboard.json: |
    {
      "dashboard": {
        "title": "PostgreSQL Monitoring",
        "tags": ["postgresql", "database"],
        "timezone": "browser",
        "panels": [
          {
            "title": "Database Connections",
            "type": "graph",
            "targets": [
              {
                "expr": "pg_stat_activity_count"
              }
            ]
          },
          {
            "title": "Query Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(pg_stat_database_xact_commit[5m])"
              }
            ]
          }
        ]
      }
    }

  redis-dashboard.json: |
    {
      "dashboard": {
        "title": "Redis Monitoring",
        "tags": ["redis", "cache"],
        "timezone": "browser",
        "panels": [
          {
            "title": "Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "redis_memory_used_bytes"
              }
            ]
          },
          {
            "title": "Commands per Second",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(redis_commands_processed_total[5m])"
              }
            ]
          }
        ]
      }
    }
