apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: mentalhealth
  labels:
    app: mentalhealth
type: Opaque
stringData:
  # IMPORTANT: These are example values and MUST be changed in production!

  # JWT Secret
  JWT_SECRET: CHANGE_ME_JWT_SECRET_32_CHARS_MIN

  # OpenAI API Key
  OPENAI_API_KEY: sk-CHANGE_ME_YOUR_OPENAI_API_KEY

  # Email Service
  SMTP_PASSWORD: CHANGE_ME_SMTP_PASSWORD

  # Encryption Key
  ENCRYPTION_KEY: CHANGE_ME_ENCRYPTION_KEY_32_BYTES

  # Session Secret
  SESSION_SECRET: CHANGE_ME_SESSION_SECRET_HERE
---
# Instructions for generating secure secrets:
#
# 1. JWT Secret (minimum 32 characters):
#    openssl rand -hex 32
#
# 2. Encryption Key (32 bytes):
#    openssl rand -base64 32
#
# 3. Session Secret:
#    openssl rand -base64 48
#
# 4. Create the secret imperatively:
#    kubectl create secret generic app-secrets \
#      --from-literal=JWT_SECRET=$(openssl rand -hex 32) \
#      --from-literal=OPENAI_API_KEY=your-actual-key \
#      --from-literal=SMTP_PASSWORD=your-smtp-password \
#      --from-literal=ENCRYPTION_KEY=$(openssl rand -base64 32) \
#      --from-literal=SESSION_SECRET=$(openssl rand -base64 48) \
#      --namespace=mentalhealth
