apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: mentalhealth
  labels:
    app: redis
type: Opaque
stringData:
  # IMPORTANT: These are example values and MUST be changed in production!
  password: CHANGE_ME_REDIS_PASSWORD_HERE
---
# Instructions for generating secure secrets:
#
# 1. Generate a strong password:
#    openssl rand -base64 32
#
# 2. Create the secret imperatively (recommended):
#    kubectl create secret generic redis-secret \
#      --from-literal=password=$(openssl rand -base64 32) \
#      --namespace=mentalhealth
