apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: mentalhealth
  labels:
    app: postgresql
data:
  database: mentalhealth_db
  postgresql.conf: |
    # PostgreSQL Configuration for High Availability

    # Connection Settings
    listen_addresses = '*'
    max_connections = 200
    superuser_reserved_connections = 3

    # Memory Settings
    shared_buffers = 512MB
    effective_cache_size = 1536MB
    maintenance_work_mem = 128MB
    work_mem = 8MB

    # WAL Settings
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby = on
    hot_standby_feedback = on

    # Checkpoints
    checkpoint_completion_target = 0.9
    checkpoint_timeout = 10min
    max_wal_size = 2GB
    min_wal_size = 1GB

    # Logging
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_truncate_on_rotation = off
    log_rotation_age = 1d
    log_rotation_size = 100MB
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_duration = off
    log_lock_waits = on
    log_statement = 'ddl'
    log_temp_files = 0

    # Performance
    random_page_cost = 1.1
    effective_io_concurrency = 200

    # Autovacuum
    autovacuum = on
    autovacuum_max_workers = 3
    autovacuum_naptime = 1min

    # Security
    ssl = off
    password_encryption = scram-sha-256
