apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: mentalhealth
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alerts@mentalhealth.example.com'
      smtp_auth_username: 'alerts@mentalhealth.example.com'
      smtp_auth_password: 'CHANGE_ME_SMTP_PASSWORD'
      smtp_require_tls: true

    # Templates
    templates:
    - '/etc/alertmanager/templates/*.tmpl'

    # Routes
    route:
      receiver: 'default-receiver'
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      routes:
      - match:
          severity: critical
        receiver: 'critical-receiver'
        continue: true
      - match:
          severity: warning
        receiver: 'warning-receiver'

    # Receivers
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: 'team@mentalhealth.example.com'
        send_resolved: true
        headers:
          Subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        html: |
          {{ range .Alerts }}
          <h3>Alert: {{ .Labels.alertname }}</h3>
          <p><strong>Status:</strong> {{ .Status }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Start Time:</strong> {{ .StartsAt }}</p>
          {{ end }}

    - name: 'critical-receiver'
      email_configs:
      - to: 'oncall@mentalhealth.example.com'
        send_resolved: true
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
      # Uncomment to add Slack notifications
      # slack_configs:
      # - api_url: 'YOUR_SLACK_WEBHOOK_URL'
      #   channel: '#alerts-critical'
      #   text: |
      #     {{ range .Alerts }}
      #     *Alert:* {{ .Labels.alertname }}
      #     *Severity:* {{ .Labels.severity }}
      #     *Summary:* {{ .Annotations.summary }}
      #     *Description:* {{ .Annotations.description }}
      #     {{ end }}

    - name: 'warning-receiver'
      email_configs:
      - to: 'team@mentalhealth.example.com'
        send_resolved: true
        headers:
          Subject: '[WARNING] {{ .GroupLabels.alertname }}'

    # Inhibit rules
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']
