---
# Fast SSD StorageClass for production workloads
# Adjust provisioner and parameters based on your cloud provider

# AWS EKS Example
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
  fsType: ext4
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
# GCP GKE Example (commented out)
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: fast-ssd
# provisioner: pd.csi.storage.gke.io
# parameters:
#   type: pd-ssd
#   replication-type: regional-pd
# allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer
# reclaimPolicy: Retain

---
# Azure AKS Example (commented out)
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: fast-ssd
# provisioner: disk.csi.azure.com
# parameters:
#   storageaccounttype: Premium_LRS
#   kind: Managed
# allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer
# reclaimPolicy: Retain
